molten-vk: Fix driver manifest library path
The relative library path in MoltenVK_icd.json needs to be adjusted to
work with the directory layout of the installed package. Otherwise, the
Vulkan loader cannot find libMoltenVK.dylib:

ERROR: [Loader Message] Code 0 : dlopen(/usr/local/share/vulkan/icd.d/.
/libMoltenVK.dylib, 0x0005): tried: '/usr/local/share/vulkan/icd.d/./li
bMoltenVK.dylib' (no such file), '/usr/local/Cellar/molten-vk/1.1.10/sh
are/vulkan/icd.d/libMoltenVK.dylib' (no such file)